#!/usr/bin/env bash
# ============================================================
# Upgrade Your Body – Automated Test & Pre-Launch Checklist
# Run: chmod +x scripts/test-checklist.sh && ./scripts/test-checklist.sh
# ============================================================

set -euo pipefail
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

PASS=0; FAIL=0; WARN=0

pass()  { echo -e "  ${GREEN}✓${NC} $1"; ((PASS++)); }
fail()  { echo -e "  ${RED}✗${NC} $1"; ((FAIL++)); }
warn()  { echo -e "  ${YELLOW}⚠${NC} $1"; ((WARN++)); }

echo -e "\n${CYAN}═══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Upgrade Your Body — Pre-Launch Test Suite${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}\n"

# ── 1. Environment ──────────────────────────────────────────
echo -e "${CYAN}1. Environment & Config${NC}"

if [ -f .env.local ]; then pass ".env.local exists"; else fail ".env.local missing"; fi

for VAR in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY NEXT_PUBLIC_APP_URL; do
  if grep -q "^${VAR}=" .env.local 2>/dev/null; then
    pass "$VAR is set"
  else
    fail "$VAR is missing from .env.local"
  fi
done

if grep -q "localhost" .env.local 2>/dev/null; then
  warn "NEXT_PUBLIC_APP_URL still points to localhost (update for production)"
fi

# ── 2. Dependencies ─────────────────────────────────────────
echo -e "\n${CYAN}2. Dependencies${NC}"

if [ -d node_modules ]; then pass "node_modules present"; else fail "node_modules missing — run npm install"; fi
if [ -f package-lock.json ]; then pass "package-lock.json exists"; else warn "No lockfile — add package-lock.json to repo"; fi

for PKG in next react @supabase/ssr @supabase/supabase-js lucide-react; do
  if [ -d "node_modules/$PKG" ]; then
    pass "$PKG installed"
  else
    fail "$PKG missing"
  fi
done

# ── 3. TypeScript & Build ───────────────────────────────────
echo -e "\n${CYAN}3. TypeScript & Build${NC}"

if command -v npx &>/dev/null; then
  echo "    Running tsc --noEmit ..."
  if npx tsc --noEmit 2>/dev/null; then
    pass "TypeScript compiles cleanly"
  else
    fail "TypeScript errors found (run: npx tsc --noEmit)"
  fi
else
  warn "npx not available — skip TS check"
fi

echo "    Running next build ..."
if npx next build 2>/dev/null; then
  pass "next build succeeds"
else
  fail "next build failed"
fi

# ── 4. Route Inventory ──────────────────────────────────────
echo -e "\n${CYAN}4. Route Inventory${NC}"

EXPECTED_PAGES=(
  "app/page.tsx"
  "app/login/page.tsx"
  "app/signup/page.tsx"
  "app/app/dashboard/page.tsx"
  "app/app/tracker/page.tsx"
  "app/app/weekly-review/page.tsx"
  "app/app/reminders/page.tsx"
  "app/app/settings/page.tsx"
)

EXPECTED_APIS=(
  "app/api/metrics/route.ts"
  "app/api/metric-entries/route.ts"
  "app/api/weekly-reviews/route.ts"
  "app/api/reminders/route.ts"
  "app/auth/callback/route.ts"
)

for PAGE in "${EXPECTED_PAGES[@]}"; do
  if [ -f "$PAGE" ]; then pass "Page: $PAGE"; else fail "Missing page: $PAGE"; fi
done

for ROUTE in "${EXPECTED_APIS[@]}"; do
  if [ -f "$ROUTE" ]; then pass "API: $ROUTE"; else fail "Missing API: $ROUTE"; fi
done

# ── 5. Security Quick-Scan ──────────────────────────────────
echo -e "\n${CYAN}5. Security${NC}"

if grep -rq "SUPABASE_SERVICE_ROLE_KEY" .env.local 2>/dev/null; then
  if grep -rq "SUPABASE_SERVICE_ROLE_KEY" app/ lib/ components/ 2>/dev/null; then
    fail "Service role key referenced in client code — use anon key only on client"
  else
    pass "Service role key not leaked to client code"
  fi
fi

if grep -q ".env" .gitignore 2>/dev/null; then
  pass ".env files in .gitignore"
else
  warn ".env not in .gitignore — secrets could be committed"
fi

# ── 6. SEO & Metadata ──────────────────────────────────────
echo -e "\n${CYAN}6. SEO & Metadata${NC}"

if grep -q "Create Next App" app/layout.tsx 2>/dev/null; then
  fail "Default 'Create Next App' title — update metadata in app/layout.tsx"
else
  pass "Custom page title set"
fi

if grep -q "Generated by create next app" app/layout.tsx 2>/dev/null; then
  fail "Default meta description — update in app/layout.tsx"
else
  pass "Custom meta description set"
fi

# ── 7. Auth Flow Checks ────────────────────────────────────
echo -e "\n${CYAN}7. Auth Flow${NC}"

if grep -q "signInWithOtp" app/login/page.tsx 2>/dev/null; then
  pass "Login uses magic link (OTP)"
else
  warn "Login method not detected"
fi

if grep -q "signInWithOtp" app/signup/page.tsx 2>/dev/null; then
  pass "Signup uses magic link (OTP)"
else
  warn "Signup method not detected"
fi

if grep -q "exchangeCodeForSession" app/auth/callback/route.ts 2>/dev/null; then
  pass "Auth callback exchanges code for session"
else
  fail "Auth callback missing session exchange"
fi

# Auth redirect goes to /dashboard but nested under /app
if grep -q "/dashboard" app/auth/callback/route.ts 2>/dev/null; then
  warn "Auth callback redirects to /dashboard — should be /app/dashboard"
fi

# ── 8. Missing Functionality ────────────────────────────────
echo -e "\n${CYAN}8. Missing / Incomplete Features${NC}"

# Reminders page uses hardcoded data
if grep -q "initialReminders" app/app/reminders/page.tsx 2>/dev/null; then
  warn "Reminders page uses hardcoded data — not connected to Supabase API"
fi

# Settings page doesn't load user data
if ! grep -q "useEffect\|getUser" app/app/settings/page.tsx 2>/dev/null; then
  warn "Settings page doesn't load authenticated user data"
fi

# No middleware for protected routes
if [ ! -f middleware.ts ] && [ ! -f app/middleware.ts ]; then
  warn "No auth middleware — protected routes (/app/*) are not guarded"
fi

# No logout button
if ! grep -rq "signOut" app/ components/ 2>/dev/null; then
  warn "No logout/signOut functionality found"
fi

# ── Summary ─────────────────────────────────────────────────
echo -e "\n${CYAN}═══════════════════════════════════════════════════${NC}"
echo -e "  ${GREEN}Passed: $PASS${NC}  |  ${RED}Failed: $FAIL${NC}  |  ${YELLOW}Warnings: $WARN${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}\n"

if [ "$FAIL" -gt 0 ]; then
  echo -e "${RED}Fix failures before deploying.${NC}\n"
  exit 1
else
  echo -e "${GREEN}No blockers — ready to proceed!${NC}\n"
  exit 0
fi
